# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpage', '0002_espmcourse_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espmcourse',
            name='category',
            field=models.CharField(blank=True, choices=[(b'Gest\xc3\xa3o', b'Gest\xc3\xa3o'), (b'Digital', b'Digital'), (b'Marketing', b'Marketing')], max_length=50, null=True),
        ),
    ]
